services:
  nats:
    image: nats:2.11
    ports:
      - "4222:4222"
      - "8222:8222"
    command: -m 8222
    restart: always

  influxdb:
    image: influxdb:2
    ports:
      - "8086:8086"
    volumes:
      - influxdb2-data:/var/lib/influxdb2
      - influxdb2-config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=7fb3232841bd35feb7a5
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=7fb3232841bd35feb7a5
      - DOCKER_INFLUXDB_INIT_ORG=acme_corp
      - DOCKER_INFLUXDB_INIT_BUCKET=the_bucket
    restart: always

  data_ingestion:
    build:
      context: .
      dockerfile: services/data_ingestion/Dockerfile
    environment:
      - NATS_URL=nats://nats:4222
    depends_on:
      - nats
    restart: always
  
  processing:
    build:
      context: .
      dockerfile: services/processing/Dockerfile
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=7fb3232841bd35feb7a5
      - INFLUXDB_ORG=acme_corp
      - INFLUXDB_BUCKET=the_bucket
      - NATS_URL=nats://nats:4222
    depends_on:
      - nats
      - influxdb
    restart: always

  alerting:
    build:
      context: .
      dockerfile: services/alerting/Dockerfile
    environment:
      - NATS_URL=nats://nats:4222
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=7fb3232841bd35feb7a5
      - INFLUXDB_ORG=acme_corp
      - INFLUXDB_BUCKET=the_bucket
      - TEMP_MIN=24.0
      - TEMP_MAX=26.0
      - HUMIDITY_MIN=35.0
      - HUMIDITY_MAX=70.0
      - ENERGY_MAX=4.0
    depends_on:
      - nats
    restart: always

  historian:
    build:
      context: .
      dockerfile: services/historian/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=7fb3232841bd35feb7a5
      - INFLUXDB_ORG=acme_corp
      - INFLUXDB_BUCKET=the_bucket
    depends_on:
      - influxdb
    restart: always


  web-app:
    build:
      context: .
      dockerfile: services/my-web-app/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - historian
      - alerting
    restart: always

  discord:
    build:
      context: .
      dockerfile: services/discord/Dockerfile
    environment:
      - DISCORD_BOT_TOKEN=MTM3MjI0MjE4MjEwNjI1MTM1Ng.GGoK3P.oA-EttJcnapDCtPqJDxhaFV_OEqoTcha7urCwo
      - NATS_URL=nats://nats:4222
    depends_on:
      - nats
      - alerting
    restart: always

volumes:
  influxdb2-data:
  influxdb2-config:
